# Generated by Django 4.0.4 on 2022-05-25 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='category_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('featured_image', models.ImageField(upload_to='product_images')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product_availability', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_portal.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Products for Rent',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=3)),
                ('rent', models.CharField(max_length=8)),
                ('is_complete', models.BooleanField(default=False)),
                ('product_rented', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_portal.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
